names <- c("kriti","saloni","swetha","pallavi","pooja")
age <- scan()
placements <- scan()
year <- scan()
d <- data.frame(names,age,placements,year)
write.csv(d,"students.csv")
a <- read.csv("students.csv")
hist(a$age,main="students and age",xlab="age",border="blue",col="pink")
hist(a$placements,main="students and placements",xlab="placements",border="blue",col="green")
hist(a$year,main="students and year",xlab="year",border="blue",col="yellow")
