names <- c("narmada","pavani","swetha","pallavi","pooja","ganga")
rank <- scan()
marks <- scan()
grade <- scan()
d <- data.frame(names,rank,marks,grade)
write.csv(d,"d.csv")
a <- read.csv("d.csv")
plot(a$rank,ylab="rank",main="students vs rank",col="blue")
plot(a$marks,ylab="marks",main="students vs marks",col="green")
plot(a$grade,ylab="grade",main="students vs grade",col="pink")
