print("enter data 1 :")
d1 <- scan()
print("enter data 2:")
d2 <- scan()
print("enter alpha value")
alpha <- scan()
n1=length(d1)
n2=length(d2)
m1=mean(d1)
sprintf("1st data mean is %f",m1)
m2=mean(d2)
sprintf("2nd data mean is %f",m2)
s1=sd(d1)
sprintf("1st data standard deviation is %f",s1)
s2=sd(d2)
sprintf("2nd data standard deviation is %f",s2)
vp=(((n1-1)*s1*s1)+((n2-1)*s2*s2))/(n1+n2-2)
sp=sqrt(vp)
sp=round(sp,3)
sprintf("combined standard deviation is %f",sp)
t <- t.test(d1,d2)
print(t)
print("Table value for two-tailed test:")
tablevalue<-qt(1-alpha/2, df=n1+n2-2)
print(round(tablevalue,digits=3))
print("Table value for one-tailed test:")
tablevalue<-qt(1-alpha, df=n1+n2-2)
print(t[1][1])
if(t[1][1]<tablevalue) {
  print("accepted")
} else {
  print("rejected")
}
